### ISSUE TITLE
Make the graph view links lighter

### ISSUE THREAD

**Issue by michaelslain** [hydescarf/Obsidian-Theme-Mado-Miniflow#10]
The contrast between the background and the links in the graph view is way too low, making it look worse.

**Comment by hydescarf** [comment]
I'm assuming graph view in light mode is fine but not dark mode. Which of the following would you prefer to have?
"A" would be close to the default theme in my view, "B" is a bit brighter
![タイトルなし](https://user-images.githubusercontent.com/56707567/185511467-5737bc7d-1a2c-47e8-8643-0a4bde4a9f39.png)

**Comment by michaelslain** [comment]
Both look great. Personally I prefer  B, but I guess that's up to personal preference.

**Comment by ryadaj** [comment]
I was thinking along the same "lines" as this @michaelslain. For the local graph view in both light and dark mode, the lines could stand out against the background a little more if possible.

Amazing theme though. My new fav.

<img width="472" alt="Screen Shot 2022-08-25 at 12 16 35" src="https://user-images.githubusercontent.com/82765301/186717142-5f9f325a-e76d-4101-a878-46d74015334c.png">

<img width="505" alt="Screen Shot 2022-08-25 at 12 16 49" src="https://user-images.githubusercontent.com/82765301/186717180-26b2a8dd-5b80-4741-a983-c2c1b9d97bf0.png">

**Comment by hydescarf** [comment]
Colours are adjusted in the latest update! https://github.com/hydescarf/Obsidian-Theme-Mado-Miniflow/commit/d7746671473e8c10908bd09cd6888a5d307c360c
We'll go with "A" for dark mode, and a little bit darker line for light mode.
