### ISSUE TITLE
Obsidian Sync Status invisible on desktop

### ISSUE THREAD

**Issue by dkeddyk** [hydescarf/Obsidian-Theme-Mado-Miniflow#11]
As the sync status of Obsidian Sync came visible in the sidebar of the mobile app with 0.2.0, it still isn't on desktop. Should be shown at least when hovering over the known position, if not all the time.

**Comment by hydescarf** [comment]
Can you elaborate more on this Sync stuff? I don't use them so I'm not sure about the issue here. Would be better if there's screenshot of what it is and how it should be.

**Comment by dkeddyk** [comment]
Of cause. On Desktop being a status-bar-item, it is placed in the status-bar. So your should figure out on how to enable checking the status-bar-items without loosing the wonderful minimal design.
![default_sync](https://user-images.githubusercontent.com/56478531/185775488-ac942675-1382-4faa-a72a-7f489a43b3b6.png)

`<div class="status-bar-item plugin-sync" aria-label="Fully synced" aria-label-position="top"><div class="status-bar-item-segment"><span class="status-bar-item-icon sync-status-icon mod-success"><svg viewBox="0 0 100 100" class="check-small" width="18" height="18"><path fill="currentColor" stroke="currentColor" d="..."></path></svg></span></div></div>`

On mobile it is in right sidebar and by that viewable with ease.
![Screenshot_20220821-061911](https://user-images.githubusercontent.com/56478531/185775476-0998ea52-e5f5-448d-ba82-02753d312f2b.png)
![Screenshot_20220821-061838](https://user-images.githubusercontent.com/56478531/185775478-47b43bcf-2493-4670-b1f9-7ed595352f19.png)

**Comment by hydescarf** [comment]
I will be turning this as an option in the Style Settings in the future.
Though, here's a snippet as a temporary fix!
```css
.status-bar{
	display:flex;
	height:0;
}

.status-bar-item.plugin-sync{
	visibility:visible;
	margin-top:-33px;
	margin-right:-26px;
}
```
This will reveal the sync icon onto the bottom-right corner of the screen.
Let me know if it works on your side!

**Comment by dkeddyk** [comment]
Thank you, the icon shows up in the lower right corner now! The snippet now makes your theme fully usable for me ;)

**Comment by hydescarf** [comment]
The theme has updated to v1.0.0, and is now supporting Style Settings!
You can now hide the status bar while leaving the Sync button to stay on float at the corner through it.
Mobile-wise, I didn't do much styling on it, so it should stay the same as default.
