### ISSUE TITLE
Please Please adapt to obsidion v1.0! 

### ISSUE THREAD

**Issue by Alex-coder251** [hydescarf/Obsidian-Theme-Mado-Miniflow#15]
your theme is so beautiful, please don't stop updating!

**Comment by hydescarf** [comment]
Thanks for the reminder of the release, and yes I do plan to adapt the styles for v1.0!
It won't be done within a short time frame, so you might need to wait for awhile though.

**Comment by Alex-coder251** [comment]
thank you!😍
