### ISSUE TITLE
[Bug] Wrong  css style of the new window when opening current panel in new window

### ISSUE THREAD

**Issue by Alex-coder251** [hydescarf/Obsidian-Theme-Mado-Miniflow#16]
1. when  i open current tag in new window directly, css style of the new windows go wrong.
![image](https://user-images.githubusercontent.com/58896036/202161588-0beb5383-17cf-4967-89ed-8e492665d1a9.png)

2. then i keep the new windows and change the theme to defualt, css style of the new windows looks normal.
![image](https://user-images.githubusercontent.com/58896036/202161619-0ed34d21-f383-4c9c-8d8d-522260d1ea25.png)

3. last i keep the new windows and change the theme back to Mado Miniflow, css style of the new windows is as shown in the figue below.
![image](https://user-images.githubusercontent.com/58896036/202161860-074e69eb-ae8e-43db-836d-720d6326f6af.png)

it dosn't look completely normal in both cases No.1 and No.2. i would be greatful if you can fix it. 🥺

**Comment by hydescarf** [comment]
I'm unable to reproduce the bug from my side.
My first assumption would be the background-wave that caused a similar issue back then, but I can't reproduce that either.

Are you able to reproduce it every single time? If so, there are a few things you can try and let me know the result:
- turn off all the plugins & snippets
- turn off background-wave through Style Settings

If possible, can you record a video of the bug? That'd be very helpful!

**Comment by Alex-coder251** [comment]
https://user-images.githubusercontent.com/58896036/202180766-7e6b6452-c4a8-43b4-b461-6bfd09990fc3.mp4

1. i close all the new windows, and reboot obsidian.

2. i open the safe mode amd turn off all my css snippets.
![image](https://user-images.githubusercontent.com/58896036/202177390-3fd608eb-4d0a-479c-92f7-af5893cb330e.png)
![image](https://user-images.githubusercontent.com/58896036/202177787-6e0a502f-abbb-4ada-b266-45ced2b2e1e0.png)

3. open current tag in new window, and then you can see the problem exits.
![image](https://user-images.githubusercontent.com/58896036/202177537-1e143cfa-3fe3-4c7f-96a1-bcb4f9ca50c9.png)
![image](https://user-images.githubusercontent.com/58896036/202178509-17eb6bbf-88d7-4a37-ac9f-30a369d2dd8b.png)

i hope this can help you.

**Comment by hydescarf** [comment]
Ah, new window, I forgot that is a thing now. That video clears up a lot, thank you!
As suspected, the background-wave is the culprit behind this.

I'll see what I can fix, as well as giving a small style fix for new window. 
In the meantime, you can turn off the background-wave (through Style Settings) to avoid the issue until I come up with a solution.
![image](https://user-images.githubusercontent.com/56707567/202187977-634543cc-1762-44d2-9950-6e1bdf3e0b1a.png)

**Comment by hydescarf** [comment]
The latest update is live, and it should now fix the issue! Let me know the result!

**Comment by Alex-coder251** [comment]
thank you so much for your hard work! 💓😭

![image](https://user-images.githubusercontent.com/58896036/202376228-381ba753-f3c9-449c-86d6-a6481931ef66.png)
