### ISSUE TITLE
Mado Miniflow in dark is not compatible with highlightr

### ISSUE THREAD

**Issue by Alex-coder251** [hydescarf/Obsidian-Theme-Mado-Miniflow#17]
[highlightr](https://github.com/chetachiezikeuzor/Highlightr-Plugin)

in light mode, the theme have a good porformance:
![image](https://user-images.githubusercontent.com/58896036/204426003-1f5628e0-4548-41fc-af24-8e60e4767f99.png)

in dark mode, it seems weird:
![image](https://user-images.githubusercontent.com/58896036/204426102-ba9879c7-7922-4bfd-a635-1361429bea7d.png)
and this is how it looks like in default theme:
![image](https://user-images.githubusercontent.com/58896036/204426243-630a7423-25d0-47dc-b46c-9406c3db29cd.png)

to closed, i'm truly grateful to your extraodinary work.💓

**Comment by hydescarf** [comment]
This is probably because the highlight style for Mado Themes is in underlined form during dark mode.
I'll make a Style Settings option to revert the style from underline to background-filled later!

**Comment by hydescarf** [comment]
The latest update now includes the option to change the style of the highlight pattern in Style Settings! Let me know if it works!

**Comment by Alex-coder251** [comment]
It works! thank you so much!💓
