### ISSUE TITLE
When searching for tags in dark mode of Mado Miniflow , the content color contrast effect is not good

### ISSUE THREAD

**Issue by Alex-coder251** [hydescarf/Obsidian-Theme-Mado-Miniflow#18]
The situation is as shown in the figure below: 
![image](https://user-images.githubusercontent.com/58896036/206825657-252a2821-ffac-478b-b7d9-109178caee7a.png)

However, light mode of Mado Miniflow dos not has this problem 
![image](https://user-images.githubusercontent.com/58896036/206825696-8d59aa5d-cbfe-4784-b7be-dee3152ceef7.png)

again, thanks for your extraordinary work💓.

**Comment by hydescarf** [comment]
It's now fixed in the latest update! Thank you for the report :D

**Comment by Alex-coder251** [comment]
thank you 💓
