### ISSUE TITLE
FR: checkboxes options

### ISSUE THREAD

**Issue by Rhydderch** [hydescarf/Obsidian-Theme-Mado-Miniflow#19]
Hello,

Thank you for this beautiful theme!

I was wondering whether you could implement the same checkbox options as the minimal theme:
https://minimal.guide/Block+types/Checklists

![image](https://user-images.githubusercontent.com/3197629/209946144-4771c0f9-6e24-4a02-943c-42873496e5ce.png)

**Comment by hydescarf** [comment]
Hey, I'm glad you enjoy the theme!
Unfortunately, I do not plan to adopt this checkbox styling to the theme.
If you need them, you can make them in your CSS Snippets instead, which would bring over to other themes easily as well!

**Comment by Rhydderch** [comment]
I completely understand - I'll go the snippet route :)!
