### ISSUE TITLE
Too much padding in tables and kanban cards

### ISSUE THREAD

**Issue by Rhydderch** [hydescarf/Obsidian-Theme-Mado-Miniflow#20]
Hello,

I noticed there is excessive padding in tables and in kanban cards (perhaps elsewhere too). It only seem to happen with text fields.
Here are some screenshots from Db folder and kanban: notice the left and right padding.

<img width="514" alt="image" src="https://user-images.githubusercontent.com/3197629/210048265-34fc554c-2fcf-4ea3-b459-5f365a2d9761.png">
<img width="253" alt="image" src="https://user-images.githubusercontent.com/3197629/210048378-4c9e56c0-390a-457d-970c-66d8d114b23d.png">

(note: I used the minimal theme before and this padding wasn't present).

Do you think you could solve this? Is it due to the theme or something else?

**Comment by hydescarf** [comment]
I'll give it a check in my free time, it shouldn't happen with normal table and kanban back in my testing.
I don't actually use plugins, but just to confirm:
- Is the first screenshot a "normal table" with another plugin used within it?
- Is the second screenshot "kanban" + "DB folder" inside the kanban?

**Comment by Rhydderch** [comment]
Sorry, I left out important information!
Indeed, it's not in normal tables.

The first screenshot is in DB folder.
The second screenshot is the normal kanban plugin.

**Comment by hydescarf** [comment]
Hey, thank you for the wait, these should now be fixed in the latest update!
Let me know if it works!

**Comment by Rhydderch** [comment]
Yes, it works! Thanks a lot for finding the time to fix this.
