### ISSUE TITLE
feature request: compact note title/edges for stacked tabs

### ISSUE THREAD

**Issue by Rhydderch** [hydescarf/Obsidian-Theme-Mado-Miniflow#24]
Hi there,

Would it be possible to set an option to have a compact title for stacked tabs, in the same way there is a compact option for tabs?

For now, the title/border is quite large
<img width="279" alt="image" src="https://user-images.githubusercontent.com/3197629/214814901-05ba98ec-8c06-4d0f-ab61-dc66a6193a09.png">

**Comment by hydescarf** [comment]
I'll look into it!

**Comment by hydescarf** [comment]
The option for it is now in the latest update! Please give it a check and let me know if it works.

**Comment by hydescarf** [comment]
Closing thread as there seems to be no issue for now!
