### ISSUE TITLE
What  the heck is Obsidian?

### ISSUE THREAD

**Issue by Mart-Bogdan** [hydescarf/Obsidian-Theme-Mado-Miniflow#26]
What app for is this theme?

Can you please clarify in README? [manifest.json](https://github.com/hydescarf/Obsidian-Theme-Mado-Miniflow/blob/main/manifest.json)  doesn't help in this regard.

**Comment by hydescarf** [comment]
Hello! This is a theme for the app Obsidian MD! https://obsidian.md/
The README is now updated with a link attached to the word "Obsidian", thank you for reporting in!

**Comment by Mart-Bogdan** [comment]
Thanks :-)
