### ISSUE TITLE
Zoom on hover or click

### ISSUE THREAD

**Issue by CodeDok** [hydescarf/Obsidian-Theme-Mado-Miniflow#27]
Hi hydescarf,

I really like this theme! Thank you for providing it for Obsidian!

Could it be possible to add the functionality to enlarge (pop out) embedded images when clicking or hovering over them?

I tried with the [snippet](https://forum.obsidian.md/t/image-zoom-click-hold-to-expand-images/5164) from Minimal Theme but my noob css skills couldn't get it to work.

Khanh

**Comment by hydescarf** [comment]
Since this doesn't really fit with the theme, we'll just go with snippet for this.
That being said, the code from where you've linked works fine as it is. Just make sure you don't have other snippets interfering with it.
If you want to hover it instead of clicking(and hold) it, replace the word `:active` to `:hover` and it should work as well.

Let me know if you still need any help with that!

**Comment by CodeDok** [comment]
You are right. I testet it with an excalidraw embed which does not work but on normal images it works. 

I tried to change the selector `.image-embed` to `excalidraw-svg:hover` but it just flickers when hovering over an embedded excalidraw drawing.

Selectors:

1. Selector: `.view-content .markdown-preview-view .excalidraw-svg:hover`
2. Selector: `.view-content .excalidraw-svg:hover img`

Thank you!

**Comment by hydescarf** [comment]
I tried out excalidraw, its drawing mode won't work at all as it uses canvas (and not html tags) to draw the components. But its markdown mode works, just as you've tried.

I don't see the flickering part, but there's one thing you'd need to add if you want it to zoom bigger when hover:
```
.view-content .excalidraw-svg:hover img {
  top:50%;
  transform:translateY(-50%);
  padding:0;
  margin:0 auto;
  width:100%;
  max-width:100%!important;
  max-height:100vh;
  object-fit:contain;
  left:0;
  right:0;
  bottom:0;
  position:absolute;
  opacity:1;
}
```
I've added `max-width:100%!important` as excalidraw limits it to 400px max.

**Comment by CodeDok** [comment]
Don't really know why it flickers in my vault even when its the only snippet activated. I don't want to further waste your time so I'll just open the pictures in a new tab when needed. 

But really appreciated your help! :)

**Comment by hydescarf** [comment]
It's alright!
It could also be possible that you have other plugins enabled, or your obsidian app is not up-to-date (there's two type of version, the app and the installer, where you'd need to reinstall manually if the installer version is currently not >1.1.9).

I tried out with a new testing vault and it's working fine on my side. If you have a video showing how it flickers, it might help!

On the other hand, there's an official discord community for obsidian you can check out! There's a section where people ask for styling help and that might help you, too!

**Comment by CodeDok** [comment]
I tried it too with a new vault. It works when its in reading view but it flickers if its in live-preview mode. 
[Flickering GIF](https://user-images.githubusercontent.com/68912385/223747472-a0e7641d-0911-4dfb-a11b-471512e80118.gif)

Haven't thought of asking on discord even though I use it daily xD. Will try it there too. Thanks again!

Edit: Removed the flickering embed
