### ISSUE TITLE
Right sidebar renders poorly with wide plugins

### ISSUE THREAD

**Issue by CodyBontecou** [hydescarf/Obsidian-Theme-Mado-Miniflow#29]
I'm not sure if this is the theme's fault or the calendar plugin I'm using, but it would be nice if the entire spacing on the right would be utilized.

<img width="1724" alt="Screenshot 2023-03-21 at 7 36 53 AM" src="https://user-images.githubusercontent.com/20440899/226694673-89635975-66a0-4253-bda2-de212a82edf5.png">

**Comment by CodyBontecou** [comment]
It looks to be from the css variable `--sidebar-size-right: 270px`. Is there an easy way to configure this within the UI rather than forking and writing my own theme?

**Comment by hydescarf** [comment]
This is indeed part of the design, but you can adjust or disable that through the Style Settings plugin!
> Style Settings > Layout Section > Sidebar Section > Fixed Width (Right) _or_ Width size if fixed (Right)

**Comment by CodyBontecou** [comment]
Oooo very nice! TIL Style Settings plugin is a thing.

Thank you! I love the theme.
