### ISSUE TITLE
about highlight-active-line

### ISSUE THREAD

**Issue by itsdrchen** [hydescarf/Obsidian-Theme-Mado-Miniflow#31]
Thank you so much for making such a wonderful theme! wonder if you can add the code [Active line highlighting in edit mode] to the theme? I wanted to add CSS snippets myself, but I really didn't get it right, so thank you so much if you could help with something!

**Comment by hydescarf** [comment]
Thank you for your comment!
As for the active line, not sure if I'm gonna add it as an option, but for now you can try the following CSS Snippet!
You can change the color as you see fit.
```css
.cm-active{
    background-color: lightgray;
}
```

**Comment by hydescarf** [comment]
Closing thread, feel free to reopen it if you have any more questions about it!
