### ISSUE TITLE
Where are this themes settings?

### ISSUE THREAD

**Issue by ScumbagScalawag** [hydescarf/Obsidian-Theme-Mado-Miniflow#35]
I'd like to enable visibility of all the menu options that this theme only reaveals if you hover over by default. Sorry for such a basic question but I just can't seem to find the settings panel shown in the README...

Thanks in advance

**Comment by hydescarf** [comment]
Thanks for the input, I should have written a small guide on that section. I'll update the README in a bit later.

You actually need a Community Plugin called "Style Settings" installed to use it.
After that, go to `Style Settings > Mado Miniflow > Layout Section > Hiding Elements`, and you'll find all the options for hidden elements.

**Comment by ScumbagScalawag** [comment]
Sweet. Much appreciated. Now this is my forever theme <3
