### ISSUE TITLE
[BUG] Color schemes don't seem to work

### ISSUE THREAD

**Issue by cyanomys** [hydescarf/Obsidian-Theme-Mado-Miniflow#37]
Hello! I'm absolutely in LOVE with this theme!! However the pre-created colorschemes available in the style settings dropdown don't seem to work. :( Just thought I'd let you know.

**Comment by hydescarf** [comment]
Are you talking about the Theme color (with default being Violette)? If so, one thing to note is that it only changes the accent color and not including background color.

Aside of that, if the option didn't work for the accent either, it's possible that you have a previous theme with a similar method that was "stuck". Try to go back to the previous theme and revert back to default colors, and then come back and check if the option is working.

Not sure if restarting the client works, but you can try that too if you haven't yet!
Let me know if you still have the problem!

**Comment by hydescarf** [comment]
Closed for inactivity
