### ISSUE TITLE
Question with left bar

### ISSUE THREAD

**Issue by talvi-frsch** [hydescarf/Obsidian-Theme-Mado-Miniflow#38]
Hello, thank you for a great theme for Obsidian. Sorry, I'm not good at programming, what can I do with this upper section, when I select the top folder on left bar? All settings are set by default

![image](https://github.com/hydescarf/Obsidian-Theme-Mado-Miniflow/assets/144930659/5d7cf0d7-0b03-4e0f-8d50-9fa70600ffc2)

**Comment by hydescarf** [comment]
Are you perhaps, talking about the visual bug on the borders?
- That border appears if you have it on focus (right-click usually does it), clicking on it or other files/folders remove that away.
- As for the visual bug (upper part missing), I have pushed an update to fix it, you can update the theme and the problem should be gone by then.

**Comment by talvi-frsch** [comment]
Yes, I'm about that border. I know clicking on something else removes it, but can I possibly change something in the css file that will move the entire list down a bit?

**Comment by hydescarf** [comment]
I have already made an update for that!
It should go down a bit now if you update to the latest version!

**Comment by talvi-frsch** [comment]
Ah, thank you very much!!
