### ISSUE TITLE
Sidebar Bug - Content not showing

### ISSUE THREAD

**Issue by rapatel0** [hydescarf/Obsidian-Theme-Mado-Miniflow#4]
Hello, I have sidebars with some pinned notes for tasks and related things. In th current implementation of the theme the content of the sidebar is squeezed despite having lots of white space availavble

<img width="975" alt="image" src="https://user-images.githubusercontent.com/18704704/183264646-a538e776-8522-4cef-8d17-37f20b8fdc33.png">

Note here is what the sidebar looks link in minimal (redacted) with the same view

<img width="933" alt="Screen Shot 2022-08-06 at 3 11 59 PM" src="https://user-images.githubusercontent.com/18704704/183264733-532a7942-e902-418e-b6c6-93adbc29d73f.png">

**Comment by hydescarf** [comment]
Thank you for reporting in! I'm aware of this actually, currently looking for solution at the moment.
The issue right now is I'm trying to give the same width to both sidebar, but the left sidebar has to be at fixed width so to align right at the same time whenever the size of the note pane is adjusted.
Will try to fix this

**Comment by hydescarf** [comment]
By the way, since I don't think I can push an update anytime soon, here's a workaround if you need it urgently.
```css
.mod-right-split .workspace-leaf-content{
	max-width:initial;
}
```
This should expand the size to the maximum of the screen.

**Comment by rapatel0** [comment]
Thanks that works beautifly

**Comment by hydescarf** [comment]
The theme has updated to v1.0.0, and is now supporting Style Settings!
You can now toggle the fixed-width for the sidebar, and if you enable it, you can adjust the length of the fixed width.
