### ISSUE TITLE
File Names Cut Off in Files Navigation Pane

### ISSUE THREAD

**Issue by andywhitaker** [hydescarf/Obsidian-Theme-Mado-Miniflow#42]
I'm noticing when using this theme that filenames are getting cut off in the files navigation pane when they are too long. This is especially an issue when there are multiple nested folders. No matter how much I expand the files navigation pane it never reveals more of the filename. Here is an example using the sandbox and Mado Miniflow theme:

![image](https://github.com/hydescarf/Obsidian-Theme-Mado-Miniflow/assets/32944047/e7574057-f7c0-4c2a-a775-49e19c23acb5)

Here is the same behavior when using the default theme:

Unexpanded:
![image](https://github.com/hydescarf/Obsidian-Theme-Mado-Miniflow/assets/32944047/3b41fea1-8f0f-4e6b-a096-9413212b3f47)

Expanded:
![image](https://github.com/hydescarf/Obsidian-Theme-Mado-Miniflow/assets/32944047/1051f3ae-7874-49ae-8a94-11deb5e1b019)

Not a huge deal but if it's fixable and you'd like to fix it I'd appreciate it. Either way I love the theme :)

Thanks!

**Comment by hydescarf** [comment]
This is intended, so that the sidebar would stick to the center regardless of its size.
That being said, I've now added an "auto-expand" option that will expand whenever its content size is changed, while sticking to the center.
You can update to the latest version, and then go into `Style Settings (3rd party plugin) > Layout Section > Sidebar Section` and find the options there!

**Comment by andywhitaker** [comment]
Thanks again for taking the time to make the change and so quickly! It's perfect! Much appreciated!

**Comment by DudeThatsErin** [comment]
The style settings seems to be backwards... I have them enabled yet it is staying fixed.
![image](https://github.com/hydescarf/Obsidian-Theme-Mado-Miniflow/assets/2681022/09eabcce-8670-4e6f-a1b4-bf21ccc77a4b)
![image](https://github.com/hydescarf/Obsidian-Theme-Mado-Miniflow/assets/2681022/daab346f-8917-463b-adf5-ba59b71d0e63)

Edit: This is the default theme. You can see on the right, the calendar plugin doesn't expand on the right side.
![image](https://github.com/hydescarf/Obsidian-Theme-Mado-Miniflow/assets/2681022/ce3110af-1554-482e-9724-fb6ce01fe01e)

When I have them disabled it works fine: 
![image](https://github.com/hydescarf/Obsidian-Theme-Mado-Miniflow/assets/2681022/b36ccb91-cd7b-40ca-8e5f-6b6f401fb158)

**Comment by hydescarf** [comment]
The new "auto-expand" option here is to cater to people who needs the sidebar to automatically expand whenever the size of the content changes, mostly occurs on long unbreakable sentences. (Although to shrink it back, they have to restart the client).
By default, the content size stays at minimum when possible, thus the size of the calendar does not change here.

If you need the calendar to fully expanded, you can disable the "Fixed Width (Right)" option;
But if you just want some wider size for the calendar, you can adjust the "Width size if fixed (Right)" for it.
Or, if you specifically only wants that calendar to expand but not the other elements in the same sidebar, you'd need a custom css snippet for that, unfortunately.

**Comment by DudeThatsErin** [comment]
Good to know. Thank you!

**Comment by hydescarf** [comment]
Also, closing thread as issue is solved.
