### ISSUE TITLE
H6 color is listed twice in style settings plugin.

### ISSUE THREAD

**Issue by DudeThatsErin** [hydescarf/Obsidian-Theme-Mado-Miniflow#43]
![image](https://github.com/hydescarf/Obsidian-Theme-Mado-Miniflow/assets/2681022/5def9f82-6f1b-43e5-95c5-d7aa33622bef)

You can see in the picture, it is listed twice.

**Comment by hydescarf** [comment]
Wow, this actually existed since v1.0.0. 😯
Thanks for reporting in!

**Comment by hydescarf** [comment]
Fixed in the latest update! (Second one is removed)
