### ISSUE TITLE
Showing Word Count

### ISSUE THREAD

**Issue by Fluffy-Tail** [hydescarf/Obsidian-Theme-Mado-Miniflow#46]
Hi, 

I really like the theme and I found I don't see word count on bottom right.
I understand showing that ugly bar isn't great.
Why don't we show just texts then?
Or if possible, I want to show it on maybe top right side of the note.
If there's, any quick solutions for me?

Thanks!

**Comment by hydescarf** [comment]
While the bottom-right bar is hidden by default, it can be toggled back on through the community plugin "Style Settings".
The option is located under "Style Settings > Layout Section > Hiding Elements > Hide Status Bar (Unhoverable)".
