### ISSUE TITLE
File explorer icons

### ISSUE THREAD

**Issue by DutchPete** [hydescarf/Obsidian-Theme-Mado-Miniflow#6]
Are you aware of this issue when you hover:

![image](https://user-images.githubusercontent.com/10794265/183288745-83550e27-6622-4f54-b772-660ceda224b2.png)

They occur at the top of the scrollbar channel.

**Comment by hydescarf** [comment]
Now I do, that's what you get for being very minimal on file numbers too lol
I ran out of time now unfortunately, will try to give a workaround next time (or make them into the update when possible)

**Comment by DutchPete** [comment]
I did not expect you to take action immediately, it is a minor issue for me because I don't use those icons, it only affects me when I want to drag the scrollbar down.

My main aim was to help you improve the theme. Just include it in the next theme update, or the one after that.

**Comment by hydescarf** [comment]
File Explorer buttons are now reverted back to their original position (Top-middle of the dock). https://github.com/hydescarf/Obsidian-Theme-Mado-Miniflow/commit/fb013389f0585408ce22c65bdff929f2530ac8d1
Unfortunately, I can't seem to think of a better way of hiding them without sacrificing user's experience, so I opted for the basic solution for this.

**Comment by DutchPete** [comment]
You solved it perfectly, as far as I am concerned, thanks a lot.
