### ISSUE TITLE
[Bug] Too Much Space After Tabs and 4 Spaces

### ISSUE THREAD

**Issue by 8veStory** [hydescarf/Obsidian-Theme-Mado-Miniflow#9]
Hi! Loving the theme so far.

I noticed there may be an issue with how the theme styles tabs or 4 spaces.

Here is an example of some text using varying amounts of spaces and tabs in the default theme.
![image](https://user-images.githubusercontent.com/29248979/185401108-6dbc87f4-7d49-4d9c-bb6b-bb95589eff06.png)

However, in both dark and light modes of this theme, for some reason every tab and group 4 spaces is shifted up by a certain amount, causing misalignment that isn't present normally.
![image](https://user-images.githubusercontent.com/29248979/185400614-8a26d854-511d-48be-a0de-30fb2d97defd.png)
![image](https://user-images.githubusercontent.com/29248979/185400658-d38a512f-aa93-481e-924c-98f8841f713f.png)

**Comment by hydescarf** [comment]
This might be a hard fix, I just realized I've been designing this without knowing the existence of number of spaces = one indent in the settings. I'll see what I can do, though there's a high chance that I might not change this and just move this to Style Settings in the future, and if I do, I'll provide you a temporary workaround for that.

**Comment by 8veStory** [comment]
Ah I see, that makes sense. And thanks!

**Comment by hydescarf** [comment]
This should be fixed in the latest update now! https://github.com/hydescarf/Obsidian-Theme-Mado-Miniflow/commit/0cafea84e7269da957801f00bbef6c9075b8d3b4

I have basically reverted the indent spacing for plain text and code block, as well as quotes too.
Indent in Listing is however remained as spacious as it is.
